from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def test_dockerfile_uses_healthz_for_image_liveness():
    dockerfile = (ROOT / "Dockerfile").read_text()
    assert "http://localhost:8080/healthz" in dockerfile
    assert "http://localhost:8080/health || exit 1" not in dockerfile


def test_deploy_script_waits_for_readyz():
    script = (ROOT / "scripts" / "deploy-compose.sh").read_text()
    assert "/readyz" in script
    assert 'http://127.0.0.1:${host_port}/health"' not in script


def test_deploy_script_does_not_autogenerate_secret_key():
    script = (ROOT / "scripts" / "deploy-compose.sh").read_text()
    assert "SECRET_KEY must be set explicitly" in script
    assert "Auto-generated by scripts/deploy-compose.sh" not in script
    assert ">> .env" not in script


def test_entrypoint_requires_explicit_secret_key():
    script = (ROOT / "scripts" / "docker-entrypoint.sh").read_text()
    assert "SECRET_KEY environment variable must be set before container startup" in script
    assert "secrets.token_hex" not in script


def test_dockerignore_excludes_non_runtime_repo_content():
    dockerignore = (ROOT / ".dockerignore").read_text()
    assert "tests/" in dockerignore
    assert "docs/" in dockerignore
    assert "ref/" in dockerignore
    assert ".git" in dockerignore


def test_chaos_check_uses_healthz_and_readyz_contracts():
    script = (ROOT / "scripts" / "m15_chaos_check.sh").read_text()
    assert "/healthz" in script
    assert "/readyz" in script
    assert '${BASE_URL}/health"' not in script


def test_ops_routes_delegate_to_split_modules():
    ops = (ROOT / "app" / "routes" / "ops.py").read_text()
    assert "from .ops_admin import register_ops_admin_routes" in ops
    assert "from .ops_api import register_ops_api_routes" in ops
    assert "register_ops_admin_routes(" in ops
    assert "register_ops_api_routes(" in ops
    assert '@app.get("/admin")' not in ops
    assert '@app.post("/api/sync")' not in ops
