#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

if [[ ! -f .env ]]; then
  if [[ -f .env.example ]]; then
    cp .env.example .env
  else
    echo "Missing .env.example; create .env manually." >&2
    exit 1
  fi
fi

if ! grep -q '^SECRET_KEY=' .env || [[ -z "$(grep '^SECRET_KEY=' .env | tail -n1 | cut -d'=' -f2-)" ]]; then
  {
    echo ""
    echo "# Auto-generated by scripts/deploy-compose.sh"
    echo "SECRET_KEY=$(python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
)"
  } >> .env
fi

echo "[deploy] Building and starting postgres, redis, app..."
docker compose up -d --build postgres redis app

published="$(docker compose port app 8080 | tail -n 1 || true)"
if [[ -z "${published}" ]]; then
  echo "[deploy] Unable to resolve published app port." >&2
  docker compose ps
  exit 1
fi
host_port="${published##*:}"

echo "[deploy] Waiting for app health..."
attempts=60
for i in $(seq 1 "${attempts}"); do
  if curl -fsS "http://127.0.0.1:${host_port}/health" >/dev/null 2>&1; then
    echo "[deploy] Service is healthy: http://127.0.0.1:${host_port}/health"
    exit 0
  fi
  sleep 2
done

echo "[deploy] App did not become healthy in time." >&2
docker compose ps
exit 1
